/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding/organization'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiOrganizationsRouteImport } from './routes/api/organizations'
import { Route as ApiOrgMembersRouteImport } from './routes/api/org-members'
import { Route as ApiInvitesRouteImport } from './routes/api/invites'
import { Route as ApiVapiStatsRouteImport } from './routes/api/vapi/stats'
import { Route as ApiVapiCallsRouteImport } from './routes/api/vapi/calls'
import { Route as ApiInvitesDeclineRouteImport } from './routes/api/invites/decline'
import { Route as ApiInvitesAcceptRouteImport } from './routes/api/invites/accept'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/onboarding/organization',
  path: '/onboarding/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationsRoute = ApiOrganizationsRouteImport.update({
  id: '/api/organizations',
  path: '/api/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrgMembersRoute = ApiOrgMembersRouteImport.update({
  id: '/api/org-members',
  path: '/api/org-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitesRoute = ApiInvitesRouteImport.update({
  id: '/api/invites',
  path: '/api/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiStatsRoute = ApiVapiStatsRouteImport.update({
  id: '/api/vapi/stats',
  path: '/api/vapi/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiCallsRoute = ApiVapiCallsRouteImport.update({
  id: '/api/vapi/calls',
  path: '/api/vapi/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvitesDeclineRoute = ApiInvitesDeclineRouteImport.update({
  id: '/decline',
  path: '/decline',
  getParentRoute: () => ApiInvitesRoute,
} as any)
const ApiInvitesAcceptRoute = ApiInvitesAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => ApiInvitesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/invites': typeof ApiInvitesRouteWithChildren
  '/api/org-members': typeof ApiOrgMembersRoute
  '/api/organizations': typeof ApiOrganizationsRoute
  '/api/users': typeof ApiUsersRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invites/accept': typeof ApiInvitesAcceptRoute
  '/api/invites/decline': typeof ApiInvitesDeclineRoute
  '/api/vapi/calls': typeof ApiVapiCallsRoute
  '/api/vapi/stats': typeof ApiVapiStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/invites': typeof ApiInvitesRouteWithChildren
  '/api/org-members': typeof ApiOrgMembersRoute
  '/api/organizations': typeof ApiOrganizationsRoute
  '/api/users': typeof ApiUsersRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invites/accept': typeof ApiInvitesAcceptRoute
  '/api/invites/decline': typeof ApiInvitesDeclineRoute
  '/api/vapi/calls': typeof ApiVapiCallsRoute
  '/api/vapi/stats': typeof ApiVapiStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invite': typeof InviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/users': typeof UsersRoute
  '/verify-email': typeof VerifyEmailRoute
  '/api/invites': typeof ApiInvitesRouteWithChildren
  '/api/org-members': typeof ApiOrgMembersRoute
  '/api/organizations': typeof ApiOrganizationsRoute
  '/api/users': typeof ApiUsersRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invites/accept': typeof ApiInvitesAcceptRoute
  '/api/invites/decline': typeof ApiInvitesDeclineRoute
  '/api/vapi/calls': typeof ApiVapiCallsRoute
  '/api/vapi/stats': typeof ApiVapiStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/invite'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/verify-email'
    | '/api/invites'
    | '/api/org-members'
    | '/api/organizations'
    | '/api/users'
    | '/onboarding/organization'
    | '/api/auth/$'
    | '/api/invites/accept'
    | '/api/invites/decline'
    | '/api/vapi/calls'
    | '/api/vapi/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/invite'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/verify-email'
    | '/api/invites'
    | '/api/org-members'
    | '/api/organizations'
    | '/api/users'
    | '/onboarding/organization'
    | '/api/auth/$'
    | '/api/invites/accept'
    | '/api/invites/decline'
    | '/api/vapi/calls'
    | '/api/vapi/stats'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/invite'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/users'
    | '/verify-email'
    | '/api/invites'
    | '/api/org-members'
    | '/api/organizations'
    | '/api/users'
    | '/onboarding/organization'
    | '/api/auth/$'
    | '/api/invites/accept'
    | '/api/invites/decline'
    | '/api/vapi/calls'
    | '/api/vapi/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InviteRoute: typeof InviteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UsersRoute: typeof UsersRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiInvitesRoute: typeof ApiInvitesRouteWithChildren
  ApiOrgMembersRoute: typeof ApiOrgMembersRoute
  ApiOrganizationsRoute: typeof ApiOrganizationsRoute
  ApiUsersRoute: typeof ApiUsersRoute
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiVapiCallsRoute: typeof ApiVapiCallsRoute
  ApiVapiStatsRoute: typeof ApiVapiStatsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations': {
      id: '/api/organizations'
      path: '/api/organizations'
      fullPath: '/api/organizations'
      preLoaderRoute: typeof ApiOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/org-members': {
      id: '/api/org-members'
      path: '/api/org-members'
      fullPath: '/api/org-members'
      preLoaderRoute: typeof ApiOrgMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites': {
      id: '/api/invites'
      path: '/api/invites'
      fullPath: '/api/invites'
      preLoaderRoute: typeof ApiInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi/stats': {
      id: '/api/vapi/stats'
      path: '/api/vapi/stats'
      fullPath: '/api/vapi/stats'
      preLoaderRoute: typeof ApiVapiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi/calls': {
      id: '/api/vapi/calls'
      path: '/api/vapi/calls'
      fullPath: '/api/vapi/calls'
      preLoaderRoute: typeof ApiVapiCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invites/decline': {
      id: '/api/invites/decline'
      path: '/decline'
      fullPath: '/api/invites/decline'
      preLoaderRoute: typeof ApiInvitesDeclineRouteImport
      parentRoute: typeof ApiInvitesRoute
    }
    '/api/invites/accept': {
      id: '/api/invites/accept'
      path: '/accept'
      fullPath: '/api/invites/accept'
      preLoaderRoute: typeof ApiInvitesAcceptRouteImport
      parentRoute: typeof ApiInvitesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiInvitesRouteChildren {
  ApiInvitesAcceptRoute: typeof ApiInvitesAcceptRoute
  ApiInvitesDeclineRoute: typeof ApiInvitesDeclineRoute
}

const ApiInvitesRouteChildren: ApiInvitesRouteChildren = {
  ApiInvitesAcceptRoute: ApiInvitesAcceptRoute,
  ApiInvitesDeclineRoute: ApiInvitesDeclineRoute,
}

const ApiInvitesRouteWithChildren = ApiInvitesRoute._addFileChildren(
  ApiInvitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InviteRoute: InviteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UsersRoute: UsersRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiInvitesRoute: ApiInvitesRouteWithChildren,
  ApiOrgMembersRoute: ApiOrgMembersRoute,
  ApiOrganizationsRoute: ApiOrganizationsRoute,
  ApiUsersRoute: ApiUsersRoute,
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiVapiCallsRoute: ApiVapiCallsRoute,
  ApiVapiStatsRoute: ApiVapiStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
